### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/etc/resolv.conf'

### ISSUE THREAD

**Issue by Ilhom550** [alexanderhale/home-assistant#10]
When I try executing `hass -v` the following error message appears:
`2021-05-12 16:14:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/hass/lib/python3.9/site-packages/homeassistant/components/dhcp/__init__.py", line 200, in async_discover
    for host in await self._discover_hosts.async_discover():
  File "/data/data/com.termux/files/home/hass/lib/python3.9/site-packages/aiodiscover/discovery.py", line 144, in async_discover
    await loop.run_in_executor(None, sys_network_data.setup)
  File "/data/data/com.termux/files/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/data/com.termux/files/home/hass/lib/python3.9/site-packages/aiodiscover/network.py", line 138, in setup
    resolvers = load_resolv_conf()
  File "/data/data/com.termux/files/home/hass/lib/python3.9/site-packages/aiodiscover/network.py", line 39, in load_resolv_conf
    with open("/data/data/com.termux/files/usr/etc/resolv.conf", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/etc/resolv.conf'`

**Comment by Ilhom550** [comment]
Fixed it by installing resolv-conf package
