### ISSUE TITLE
Homeassistant.setup dhcp error

### ISSUE THREAD

**Issue by njnicolau** [alexanderhale/home-assistant#12]
Hi, I installed HA <= 2021.4 and it works great!
But when I install HA <=2021.5 shows this error:

2021-07-25 19:19:13 ERROR (MainThread) [homeassistant.setup] Setup failed for dhcp: unknown error
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/homeassistant/setup.py", line 200, in _async_setup_component
    component = integration.get_component()
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/homeassistant/loader.py", line 485, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/data/data/com.termux/files/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/homeassistant/components/dhcp/__init__.py", line 17, in <module>
    from scapy.arch.common import compile_filter
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/scapy/arch/__init__.py", line 135, in <module>
    _set_conf_sockets()  # Apply config
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/scapy/config.py", line 618, in _set_conf_sockets
    conf.ifaces.reload()
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/scapy/interfaces.py", line 238, in reload
    self._reload_provs()
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/scapy/interfaces.py", line 234, in _reload_provs
    self._load(prov.reload(), prov)
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/scapy/interfaces.py", line 53, in reload
    return self.load()
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/scapy/arch/linux.py", line 420, in load
    get_if_raw_hwaddr(i, siocgifhwaddr=SIOCGIFHWADDR)[1]
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/scapy/arch/common.py", line 87, in get_if_raw_hwaddr
    get_if(iff, siocgifhwaddr)
  File "/data/data/com.termux/files/home/hass2/lib/python3.9/site-packages/scapy/arch/common.py", line 65, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
PermissionError: [Errno 13] Permission denied

Any ideas for this error?
Thankyou

**Comment by brainstorm** [comment]
Haven't seen your error with my recent installation: https://github.com/home-assistant/core/issues/74608 ... doesn't look as critical as yours, but it requires some work/fixes upsream, I reckon.
